### PR TITLE
Fix a test suite `ImportError` due to a missing dependency

### LINKED ISSUE #253: CI and test suite are failing
The test suite is currently failing, both locally and in CI ([recent example against `main`](https://github.com/pallets/quart/actions/runs/5564594450/jobs/10164283497)).

```
____________________ ERROR collecting tests/test_config.py _____________________
ImportError while importing test module '/home/runner/work/quart/quart/tests/test_config.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_config.py:8: in <module>
    import toml
E   ModuleNotFoundError: No module named 'toml'
```

Environment:

- Python version: All tested Python versions
- Quart version: Latest code on `main` branch

### PR DESCRIPTION
**Pull request by kurtmckee**
This PR introduces `toml` as a test suite dependency (and as a Poetry dev group dependency) to ensure that `test_config.py` can be imported.

Things not addressed in this PR:

* I attempted to add tests for `tomllib` (for Python 3.11 and higher) and `tomli` (for Python 3.10 and lower) as this is the TOML parser included in the Python standard library moving forward. However, it requires the input file to be opened in binary mode so I abandoned this work as out-of-scope.
* mypy 1.4.1 is upset about a protocol/implementation mismatch. I did not dive into this.
* mypy is upset about `readline.set_completer()` in `cli.py` not existing when running on Windows. I attempted to resolve this but found that `cli.py` failed multiple pre-commit hooks, and it would make the overall PR unwieldy.

I recommend running `pre-commit run --all --all-files` on the repo. Also, many pre-commit hooks are very out-of-date. It looks like pre-commit.ci isn't enabled for this repo, and I recommend enabling it. The `ci` configuration in `.pre-commit-config.yaml` may need to be updated as well, or removed.

- Fixes #253

Checklist:

- [x] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change. (_Tests were already failing_)
- [ ] Add or update relevant docs, in the docs folder and in code.
- [ ] Add an entry in `CHANGES.rst` summarizing the change and linking to the issue. (_This work seems too small to add to `CHANGES.rst`_)
- [ ] Add `.. versionchanged::` entries in any relevant code docs. (_Not relevant_)
- [x] Run `pre-commit` hooks and fix any issues. (_Many files in repo already fail pre-commit hook checks, nothing new was introduced in this PR_)
- [x] Run `pytest` and `tox`, no tests failed. (_Test suite is fixed, linters are already failing_)

### CODE REVIEW

**Comment by kurtmckee** [comment]
Hello! Please let me know if there's anything needed to push this PR over the finish line. :grinning:

**Comment by davidism** [comment]
As with all other PRs, maintainer time is what's needed. We'll get to it when we have time. ;-)

**Comment by pgjones** [comment]
Thanks, but toml was removed in 4fd2c7473b776408647dec3cf9400c27e272cf41

**Comment by kurtmckee** [comment]
I don't think this can be closed. The test suite continues to fail on a fresh clone of this repo due to `ImportError`.

`toml` was removed as a direct dependency, but the test suite continues to fail because `toml` isn't installed when the test suite runs.

**Comment by kurtmckee** [comment]
Hmm...I've cloned the quart repo but I'm not able to run any of the tests anymore. They all fail with:

```
Collecting flask@ git+https://github.com/pallets/flask.git@main
  Cloning https://github.com/pallets/flask.git (to revision main) to /tmp/pip-install-kxwm0n6z/flask_778fcda25771402cb5a65c01224e4f8d
  Running command git clone --filter=blob:none --quiet https://github.com/pallets/flask.git /tmp/pip-install-kxwm0n6z/flask_778fcda25771402cb5a65c01224e4f8d
  error: object 0b404df8c030cdeaca7b373956c3a697efd32f78: zeroPaddedFilemode: contains zero-padded file modes
  fatal: fsck error in packed object
  fatal: fetch-pack: invalid index-pack output
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/pallets/flask.git /tmp/pip-install-kxwm0n6z/flask_778fcda25771402cb5a65c01224e4f8d did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
```

This PR can stay closed.

**Comment by pgjones** [comment]
Does the flask install issue depend on the pip version?

**Comment by kurtmckee** [comment]
I traced it this morning and discovered the root cause! It's occurring because when pip invokes git, git is inheriting my global git config, which automatically fscks git objects.

I found that this is [a known issue in Flask's git history](https://github.com/pallets/flask/issues/2029). I've submitted a ticket to pip to suggest [a possible way to resolve this](https://github.com/pypa/pip/issues/12262).

In the meantime, I'm able to change my global git config as needed. :+1: 

Thanks for following up about this!

**Pull request closed without merging**
